// Generated by `cargo bake --regenerate`; do not edit.

use bake_agent_context as _;
use bake_cargo as _;
use bake_license as _;
use bake_releases as _;
use bake_test_rust as _;
use socketry_project as _;
