[package]
name = "bake-rust-tasks"
version = "0.0.0"
edition.workspace = true
publish = false

[dependencies]
socketry-project = "0.3"
bake = { version = "0.17.4", path = ".." }
bake-agent-context = { version = "0.2" }
bake-test-rust = { version = "0.2" }
bake-releases = { version = "0.2.1" }
bake-cargo = { version = "0.2.9" }
bake-license = { version = "0.1.1" }

[dev-dependencies]
tempfile.workspace = true
