[package]
name = "bake-rust-tasks"
version = "0.0.0"
edition.workspace = true
publish = false

[dependencies]
socketry-project = ">=0.3.3"
bake = { version = "0.19.0", path = ".." }
bake-agent-context = { version = "0.3.0" }
bake-test-rust = { version = "0.2.2" }
bake-releases = { version = "0.3.0" }
bake-cargo = { version = "0.4.0" }
bake-license = { version = "0.2.0" }

[dev-dependencies]
tempfile.workspace = true
